apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  namespace: webapp
  name: database-creds
spec:
  vaultAuthRef: static-auth
  mount: database
  path: creds/webapp-role
  destination:
    create: true
    name: postgres
  rolloutRestartTargets:
  - kind: Deployment
    name: webapp
