apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: development
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: nginx
        name: nginx
        env:
        - name: db_host
          valueFrom:
            secretKeyRef:
              name: dbcred
              key: db_host
        - name: db_name
          valueFrom:
            secretKeyRef:
              name: dbcred
              key: db_name
        - name: db_user
          valueFrom:
            secretKeyRef:
              name: dbcred
              key: username
        - name: db_pass
          valueFrom:
            secretKeyRef:
              name: dbcred
              key: password
        

