apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp
  namespace: development
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: nginx
        name: nginx
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: dbcred
              key: db_host
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: dbcred
              key: db_name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: dbcred
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dbcred
              key: password
        

