apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: development
  name: vault-static-secret-dbcred
spec:
  vaultAuthRef: static-auth
  mount: kv-v2
  type: kv-v2
  path: webapp/dbcred
  refreshAfter: 10s
  destination:
    create: true
    name: dbcred
  rolloutRestartTargets:
  - kind: Deployment
    name: webapp
