apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: webapp
spec:
  # vaultConnectionRef: default
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: webapp
    serviceAccount: dev-vault-svc-account
    audiences:
      - vault
